Repository hell-study-class/Coding-Test, pull requests merged in 2024-08, with the labels that each got.

#22 [20240729] 구태형_8회차 문제 풀이 5주차
  [6회차] graph/태형/G4_11404.py
  [6회차] graph/태형/G4_1956.py
  [6회차] graph/태형/G4_2458.py
  [6회차] graph/태형/G4_2573.py
  [6회차] graph/태형/S1_11403.py
  [6회차] graph/태형/S1_1389.py
  [8회차] 트리순회 /태형/G3_14725.py
  [8회차] 트리순회 /태형/G3_7432.py
  [8회차] 트리순회 /태형/G4_1967.py
  [8회차] 트리순회 /태형/G4_5052.py
  [8회차] 트리순회 /태형/G4_5639.py
  [8회차] 트리순회 /태형/S4_9372.py
  [9회차] 백트래킹/태형/G2_13502.py
  [9회차] 백트래킹/태형/S1_14888.py
  [9회차] 백트래킹/태형/S2_6603.py
  [9회차] 백트래킹/태형/S3_15649.py
  [9회차] 백트래킹/태형/S3_15650.py
  [9회차] 백트래킹/태형/S3_15651.py
  [9회차] 백트래킹/태형/S3_15652.py
  [9회차] 백트래킹/태형/S3_15654.py
  [9회차] 백트래킹/태형/S3_15655.py
  [9회차] 백트래킹/태형/S3_15657.py
Labels: 트리 순회, 백트래킹, 5주차

#24 [20240801] 정우용_9회차 문제 풀이 5주차
  [9회차] 백트래킹/우용/S3_15649.java
  [9회차] 백트래킹/우용/S3_15650.java
  [9회차] 백트래킹/우용/S3_15651.java
  [9회차] 백트래킹/우용/S3_18429.java
  [9회차] 백트래킹/우용/S3_2992.java
  [9회차] 백트래킹/우용/S4_5568.java
Labels: 백트래킹, 5주차

#25 [20240801] 임창희_9회차 문제 풀이 5주차
  [9회차] 백트래킹/창희/S1_14888.java
  [9회차] 백트래킹/창희/S2_6603.java
  [9회차] 백트래킹/창희/S3_15649.java
  [9회차] 백트래킹/창희/S3_15650.java
  [9회차] 백트래킹/창희/S3_15651.java
  [9회차] 백트래킹/창희/S3_15652.java
Labels: 백트래킹, 5주차

#26 [20240801] 맹인호_9회차 문제 풀이 5주차
  [9회차] 백트래킹/인호/G4_9663.py
  [9회차] 백트래킹/인호/S3_15649.py
  [9회차] 백트래킹/인호/S3_15650.py
Labels: 백트래킹, 5주차

#27 [20240805] 정우용_10회차 문제 풀이 6주차
  [10회차] 백트래킹/우용/S1_14889.java
  [10회차] 백트래킹/우용/S1_2529.java
  [10회차] 백트래킹/우용/S2_10819.java
  [10회차] 백트래킹/우용/S2_10971.java
  [10회차] 백트래킹/우용/S2_1182.java
  [10회차] 백트래킹/우용/S2_2961.java
  [10회차] 백트래킹/우용/S3_10974.java
Labels: 백트래킹, 6주차

#28 [20240805] 맹인호_10회차 문제 풀이 6주차
  [10회차] 백트래킹/인호/G5_15686.py
  [10회차] 백트래킹/인호/G5_1759.py
  [10회차] 백트래킹/인호/S1_14889.py
  [10회차] 백트래킹/인호/S3_15651.py
  [10회차] 백트래킹/인호/S3_15652.py
  [10회차] 백트래킹/인호/S3_15654.py
  [10회차] 백트래킹/인호/S3_15655.py
  [10회차] 백트래킹/인호/S3_15656.py
  [10회차] 백트래킹/인호/S3_15657.py
Labels: 백트래킹, 6주차

#30 [20240805] 구태형_10회차 문제 풀이 6주차
  [10회차] 백트래킹/태형/G4_2239.py
  [10회차] 백트래킹/태형/G4_2580.py
  [10회차] 백트래킹/태형/G5_15686.py
  [10회차] 백트래킹/태형/S1_14889.py
  [10회차] 백트래킹/태형/S2_10819.py
  [10회차] 백트래킹/태형/S2_1182.py
  [10회차] 백트래킹/태형/S3_10974.py
Labels: 백트래킹, 6주차

#29 [20240805] 임창희_10회차 문제 풀이 6주차
  [10회차] 백트래킹/창희/G3_1941.java
  [10회차] 백트래킹/창희/G5_1759.java
  [10회차] 백트래킹/창희/S1_14889.java
  [10회차] 백트래킹/창희/S1_16198.java
  [10회차] 백트래킹/창희/S1_2529.java
  [10회차] 백트래킹/창희/S3_15654.java
  [10회차] 백트래킹/창희/S3_15657.java
  [11회차] 그리디/창희/B3_10162.java
  [11회차] 그리디/창희/B5_10950.java
  [11회차] 그리디/창희/S3_2503.java
  [11회차] 그리디/창희/S5_1343.java
  [11회차] 그리디/창희/S5_2740.java
  [11회차] 그리디/창희/S5_4673.java
Labels: 백트래킹, 6주차

#32 [20240808] 맹인호_11회차 문제 풀이 6주차
  [11회차] 그리디/인호/B3_2720.py
  [11회차] 그리디/인호/G4_1339.py
  [11회차] 그리디/인호/G4_1715.py
  [11회차] 그리디/인호/README.md
  [11회차] 그리디/인호/S2_1541.py
  [11회차] 그리디/인호/S4_11047.py
  [11회차] 그리디/인호/S4_11399.py
Labels: 6주차, greedy

#31 [20240808] 정우용_11회차 문제 풀이 6주차
  [11회차] 그리디/우용/S4_1026.java
  [11회차] 그리디/우용/S4_11047.java
  [11회차] 그리디/우용/S4_11399.java
Labels: 6주차, greedy

#33 [20240808] 구태형_11회차 문제 풀이 6주차
  [11회차] 그리디/태형/B1_4796.py
  [11회차] 그리디/태형/B3_10162.py
  [11회차] 그리디/태형/B3_2720.py
  [11회차] 그리디/태형/G4_1339.py
  [11회차] 그리디/태형/G4_1744.py
  [11회차] 그리디/태형/G5_1715.py
  [11회차] 그리디/태형/S1_1931.py
  [11회차] 그리디/태형/S1_1946.py
  [11회차] 그리디/태형/S2_1541.py
  [11회차] 그리디/태형/S2_1541_.py
  [11회차] 그리디/태형/S2_16953.py
  [11회차] 그리디/태형/S3_13305.py
  [11회차] 그리디/태형/S4_11047.py
  [11회차] 그리디/태형/S4_11399.py
  [11회차] 그리디/태형/S5_1439.py
Labels: 6주차, greedy

#34 [20240812] 맹인호_12회차 문제 풀이 7주차
  [12회차] 그리디/인호/G1_1700.py
  [12회차] 그리디/인호/G2_2437.py
  [12회차] 그리디/인호/G5_11000.py
  [12회차] 그리디/인호/G5_12904.py
  [12회차] 그리디/인호/G5_2212.py
Labels: greedy, 7주차

#37 [20240812] 구태형_12회차 문제 풀이 7주차
  [12회차] 그리디/태형/G2_1202.py
  [12회차] 그리디/태형/G2_2437.py
  [12회차] 그리디/태형/G3_2812.py
  [12회차] 그리디/태형/G5_1092.py
  [12회차] 그리디/태형/G5_11000.py
  [12회차] 그리디/태형/G5_1202.py
  [12회차] 그리디/태형/G5_12904.py
  [12회차] 그리디/태형/S4_1026.py
Labels: greedy, 7주차

#35 [20240812] 정우용_12회차 문제 풀이 7주차
  [12회차] 그리디/우용/README.md
  [12회차] 그리디/우용/S4_1049.java
  [12회차] 그리디/우용/S4_2847.java
Labels: greedy, 7주차

#36 [20240812] 임창희_12회차 문제 풀이 7주차
  [12회차] 그리디/창희/Lv1_161989.java
  [12회차] 그리디/창희/Lv1_161990.java
  [12회차] 그리디/창희/Lv1_172928.java
  [12회차] 그리디/창희/Lv1_176963.java
  [12회차] 그리디/창희/Lv1_42862.java
  [12회차] 그리디/창희/Lv1_77484.java
  [13회차] dp/창희/Lv1_138477.java
  [13회차] dp/창희/Lv1_160586.java
  [13회차] dp/창희/Lv2_12945.java
  [13회차] dp/창희/S1_1149.java
  [13회차] dp/창희/S5_1010.java
Labels: 구현

#38 [20240816] 맹인호_13회차 문제 풀이 7주차
  [13회차] dp/인호/121. Best Time to Buy and Sell Stock.py
  [13회차] dp/인호/N으로표현.java
  [13회차] dp/인호/S4_2839.py
  [13회차] dp/인호/[leetcode] 70_Climbing Stairs.py
  [13회차] dp/인호/[leetcode]118_Pascal's Triangle .py
  [13회차] dp/인호/[leetcode]119. Pascal's Triangle II.py
  [13회차] dp/인호/네트워크.java
  [13회차] dp/인호/도둑질.java
  [13회차] dp/인호/등굣길.java
  [13회차] dp/인호/정수삼각형.java
  [13회차] dp/인호/타겟넘버.java
  [14회차] dp/인호/Readme.md
Labels: 7주차, DP

#42 [20240823] 맹인호_14회차 문제 풀이 8주차
  [14회차] dp/인호/G3_4179.py
  [14회차] dp/인호/G5_1074.py
  [14회차] dp/인호/G5_11729.py
  [14회차] dp/인호/G5_7576.java
  [14회차] dp/인호/Lv3 여행경로.java
  [14회차] dp/인호/S1_1629.py
  [14회차] dp/인호/S1_1697.py
  [14회차] dp/인호/S1_1926.java
  [14회차] dp/인호/S1_2178.java
  [14회차] dp/인호/S4_28086.java
  [14회차] dp/인호/단어 변환.py
  [15회차] 비트 마스킹/인호/readme.md
Labels: bfs/dfs, DP, 8주차

#45 [20240826] 구태형_15회차 문제 풀이 8주차
  [15회차] 비트 마스킹/JadenCase 문자열 만들기.py
  [15회차] 비트 마스킹/sql/3월에 태어난 여성 회원 목록 출력하기.sql
  [15회차] 비트 마스킹/sql/DATETIME에서 DATE로 형 변환.sql
  [15회차] 비트 마스킹/sql/NULL 처리하기.sql
  [15회차] 비트 마스킹/sql/ROOT 아이템 구하기.sql
  [15회차] 비트 마스킹/sql/가격이 제일 비싼 식품의 정보 출력하기.sql
  [15회차] 비트 마스킹/sql/고양이와 개는 몇 마리 있을까.sql
  [15회차] 비트 마스킹/sql/동명 동물 수 찾기.sql
  [15회차] 비트 마스킹/sql/동물 수 구하기.sql
  [15회차] 비트 마스킹/sql/루시와 엘라 찾기.sql
  [15회차] 비트 마스킹/sql/물고기 종류 별 잡은 수 구하기.sql
  [15회차] 비트 마스킹/sql/상품 별 오프라인 매출 구하기.sql
  [15회차] 비트 마스킹/sql/성분으로 구분한 아이스크림 총 주문량.sql
  [15회차] 비트 마스킹/sql/연도 별 평균 미세먼지 농도 조회하기.sql
  [15회차] 비트 마스킹/sql/월별 잡은 물고기 수 구하기.sql
  [15회차] 비트 마스킹/sql/이름에 el이 들어가는 동물 찾기.sql
  [15회차] 비트 마스킹/sql/자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기.sql
  [15회차] 비트 마스킹/sql/조건에 맞는 도서와 저자 리스트 출력하기.sql
  [15회차] 비트 마스킹/sql/조건에 맞는 아이템들의 가격의 총합 구하기.sql
  [15회차] 비트 마스킹/sql/조건에 부합하는 중고거래 상태 조회하기.sql
  [15회차] 비트 마스킹/sql/중복 제거하기.sql
  [15회차] 비트 마스킹/sql/중성화 여부 파악하기.sql
  [15회차] 비트 마스킹/sql/진료과별 총 예약 횟수 출력하기.sql
  [15회차] 비트 마스킹/sql/최솟값 구하기.sql
  [15회차] 비트 마스킹/sql/카테고리 별 상품 개수 구하기.sql
  [15회차] 비트 마스킹/게임 맵 최단거리.py
  [15회차] 비트 마스킹/다음 큰 숫자.py
  [15회차] 비트 마스킹/땅따먹기.py
  [15회차] 비트 마스킹/영어 끝말잇기.py
  [15회차] 비트 마스킹/올바른 괄호.py
  [15회차] 비트 마스킹/이진 변환 반복하기.py
  [15회차] 비트 마스킹/최댓값과 최솟값.py
  [15회차] 비트 마스킹/최솟값 만들기.py
  [15회차] 비트 마스킹/타겟넘버.py
Labels: 8주차

#46 [20240829] 맹인호_16회차 문제 풀이 9주차
  [16회차] 비트 마스킹/인호/S2_9184.java
  [16회차] 비트 마스킹/인호/S5_1010.java
  [16회차] 비트 마스킹/인호/모음사전.java
Labels: bfs/dfs, DP, 9주차
